import { useCallback, useState } from "react";
import jsPDF from "jspdf";
import html2canvas from "html2canvas";

interface ExportOptions {
  filename?: string;
  title?: string;
  subtitle?: string;
}

export function usePdfExport() {
  const [isExporting, setIsExporting] = useState(false);

  const exportToPdf = useCallback(async (
    elementId: string,
    options: ExportOptions = {}
  ) => {
    const { 
      filename = "herd-projection-report.pdf",
      title = "Herd Projection Report",
      subtitle = "Generated by FHPS"
    } = options;

    setIsExporting(true);

    try {
      const element = document.getElementById(elementId);
      if (!element) throw new Error("Element not found");

      // Detect current theme
      const isDark = document.documentElement.classList.contains("dark");

      // Temporarily expand all scroll containers for full capture
      const scrollContainers = element.querySelectorAll<HTMLElement>('[class*="max-h-"], [class*="overflow"]');
      const origStyles: { el: HTMLElement; maxHeight: string; overflow: string; overflowY: string }[] = [];

      origStyles.push({ el: element, maxHeight: element.style.maxHeight, overflow: element.style.overflow, overflowY: element.style.overflowY });
      element.style.maxHeight = "none";
      element.style.overflow = "visible";
      element.style.overflowY = "visible";

      scrollContainers.forEach(el => {
        origStyles.push({ el, maxHeight: el.style.maxHeight, overflow: el.style.overflow, overflowY: el.style.overflowY });
        el.style.maxHeight = "none";
        el.style.overflow = "visible";
        el.style.overflowY = "visible";
      });

      // Brief delay for repaint
      await new Promise(r => setTimeout(r, 200));

      // Capture with background matching current theme
      const bgColor = isDark ? "#1a1510" : "#faf8f5";
      const canvas = await html2canvas(element, {
        scale: 2,
        useCORS: true,
        logging: false,
        backgroundColor: bgColor,
        windowWidth: 1200,
      });

      // Restore scroll styles
      origStyles.forEach(({ el, maxHeight, overflow, overflowY }) => {
        el.style.maxHeight = maxHeight;
        el.style.overflow = overflow;
        el.style.overflowY = overflowY;
      });

      const pdf = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
      const pageWidth = pdf.internal.pageSize.getWidth();
      const pageHeight = pdf.internal.pageSize.getHeight();
      const margin = 15;
      const contentWidth = pageWidth - (margin * 2);

      // Theme-aware header colors
      const headerBg = isDark ? { r: 26, g: 21, b: 16 } : { r: 59, g: 102, b: 67 };
      const headerText = { r: 255, g: 255, b: 255 };
      const accentBar = isDark ? { r: 180, g: 160, b: 100 } : { r: 200, g: 180, b: 120 };
      const footerText = isDark ? { r: 160, g: 150, b: 140 } : { r: 140, g: 140, b: 140 };
      const footerLine = isDark ? { r: 60, g: 50, b: 40 } : { r: 200, g: 200, b: 200 };

      // ─── Header ───
      pdf.setFillColor(headerBg.r, headerBg.g, headerBg.b);
      pdf.rect(0, 0, pageWidth, 38, "F");

      pdf.setTextColor(headerText.r, headerText.g, headerText.b);
      pdf.setFontSize(24);
      pdf.setFont("helvetica", "bold");
      pdf.text(title, margin, 18);

      pdf.setFontSize(10);
      pdf.setFont("helvetica", "normal");
      pdf.text(subtitle, margin, 28);

      const dateStr = new Date().toLocaleDateString("en-US", {
        year: "numeric", month: "long", day: "numeric"
      });
      pdf.text(`Generated: ${dateStr}`, pageWidth - margin, 28, { align: "right" });

      // Accent bar
      pdf.setFillColor(accentBar.r, accentBar.g, accentBar.b);
      pdf.rect(0, 38, pageWidth, 1.5, "F");

      // ─── Content ───
      const imgWidth = contentWidth;
      const imgHeight = (canvas.height * imgWidth) / canvas.width;
      const startY = 48;

      let remainingHeight = imgHeight;
      let currentY = startY;
      let sourceY = 0;
      let pageNum = 1;

      while (remainingHeight > 0) {
        const footerSpace = 16;
        const availableHeight = pageHeight - currentY - footerSpace;
        const drawHeight = Math.min(remainingHeight, availableHeight);
        const sourceHeight = (drawHeight / imgHeight) * canvas.height;

        const croppedCanvas = document.createElement("canvas");
        croppedCanvas.width = canvas.width;
        croppedCanvas.height = sourceHeight;
        const ctx = croppedCanvas.getContext("2d");

        if (ctx) {
          ctx.drawImage(canvas, 0, sourceY, canvas.width, sourceHeight, 0, 0, canvas.width, sourceHeight);
          const croppedImgData = croppedCanvas.toDataURL("image/png");
          pdf.addImage(croppedImgData, "PNG", margin, currentY, imgWidth, drawHeight);
        }

        // ─── Footer ───
        pdf.setDrawColor(footerLine.r, footerLine.g, footerLine.b);
        pdf.line(margin, pageHeight - 14, pageWidth - margin, pageHeight - 14);

        pdf.setTextColor(footerText.r, footerText.g, footerText.b);
        pdf.setFontSize(8);
        pdf.text("FHPS • Fibonacci-Based Herd Projection System", margin, pageHeight - 8);
        pdf.text(`Page ${pageNum}`, pageWidth - margin, pageHeight - 8, { align: "right" });

        remainingHeight -= drawHeight;
        sourceY += sourceHeight;

        if (remainingHeight > 0) {
          pdf.addPage();
          pageNum++;
          currentY = margin;
        }
      }

      pdf.save(filename);
    } catch (error) {
      console.error("PDF export failed:", error);
      throw error;
    } finally {
      setIsExporting(false);
    }
  }, []);

  return { exportToPdf, isExporting };
}
