import { useCallback, useState } from "react";
import jsPDF from "jspdf";
import html2canvas from "html2canvas";

interface ExportOptions {
  filename?: string;
  title?: string;
  subtitle?: string;
}

export function usePdfExport() {
  const [isExporting, setIsExporting] = useState(false);

  const exportToPdf = useCallback(async (
    elementId: string,
    options: ExportOptions = {}
  ) => {
    const { 
      filename = "herd-projection-report.pdf",
      title = "Herd Projection Report",
      subtitle = "Generated by FHPS"
    } = options;

    setIsExporting(true);

    try {
      const element = document.getElementById(elementId);
      if (!element) {
        throw new Error("Element not found");
      }

      // Temporarily expand element for better capture
      const origMaxHeight = element.style.maxHeight;
      const origOverflow = element.style.overflow;
      element.style.maxHeight = "none";
      element.style.overflow = "visible";

      const canvas = await html2canvas(element, {
        scale: 2,
        useCORS: true,
        logging: false,
        backgroundColor: "#faf8f5",
        windowWidth: 1200,
      });

      element.style.maxHeight = origMaxHeight;
      element.style.overflow = origOverflow;

      const imgData = canvas.toDataURL("image/png");
      const pdf = new jsPDF({
        orientation: "portrait",
        unit: "mm",
        format: "a4",
      });

      const pageWidth = pdf.internal.pageSize.getWidth();
      const pageHeight = pdf.internal.pageSize.getHeight();
      const margin = 15;
      const contentWidth = pageWidth - (margin * 2);

      // ─── Header ───
      pdf.setFillColor(59, 102, 67);
      pdf.rect(0, 0, pageWidth, 38, "F");
      
      pdf.setTextColor(255, 255, 255);
      pdf.setFontSize(24);
      pdf.setFont("helvetica", "bold");
      pdf.text(title, margin, 18);
      
      pdf.setFontSize(10);
      pdf.setFont("helvetica", "normal");
      pdf.text(subtitle, margin, 28);
      
      const dateStr = new Date().toLocaleDateString("en-US", { 
        year: "numeric", month: "long", day: "numeric" 
      });
      pdf.text(`Generated: ${dateStr}`, pageWidth - margin, 28, { align: "right" });

      // Thin accent bar under header
      pdf.setFillColor(200, 180, 120);
      pdf.rect(0, 38, pageWidth, 1.5, "F");

      // ─── Content ───
      const imgWidth = contentWidth;
      const imgHeight = (canvas.height * imgWidth) / canvas.width;
      const startY = 48;

      let remainingHeight = imgHeight;
      let currentY = startY;
      let sourceY = 0;
      let pageNum = 1;

      while (remainingHeight > 0) {
        const footerSpace = 16;
        const availableHeight = pageHeight - currentY - footerSpace;
        const drawHeight = Math.min(remainingHeight, availableHeight);
        const sourceHeight = (drawHeight / imgHeight) * canvas.height;

        const croppedCanvas = document.createElement("canvas");
        croppedCanvas.width = canvas.width;
        croppedCanvas.height = sourceHeight;
        const ctx = croppedCanvas.getContext("2d");
        
        if (ctx) {
          ctx.drawImage(
            canvas,
            0, sourceY,
            canvas.width, sourceHeight,
            0, 0,
            canvas.width, sourceHeight
          );
          
          const croppedImgData = croppedCanvas.toDataURL("image/png");
          pdf.addImage(croppedImgData, "PNG", margin, currentY, imgWidth, drawHeight);
        }

        // ─── Footer on every page ───
        pdf.setDrawColor(200, 200, 200);
        pdf.line(margin, pageHeight - 14, pageWidth - margin, pageHeight - 14);
        
        pdf.setTextColor(140, 140, 140);
        pdf.setFontSize(8);
        pdf.text(
          "FHPS • Fibonacci-Based Herd Projection System",
          margin,
          pageHeight - 8
        );
        pdf.text(
          `Page ${pageNum}`,
          pageWidth - margin,
          pageHeight - 8,
          { align: "right" }
        );

        remainingHeight -= drawHeight;
        sourceY += sourceHeight;

        if (remainingHeight > 0) {
          pdf.addPage();
          pageNum++;
          currentY = margin;
        }
      }

      pdf.save(filename);
    } catch (error) {
      console.error("PDF export failed:", error);
      throw error;
    } finally {
      setIsExporting(false);
    }
  }, []);

  return { exportToPdf, isExporting };
}