import { useCallback, useState } from "react";
import jsPDF from "jspdf";
import html2canvas from "html2canvas";

interface ExportOptions {
  filename?: string;
  title?: string;
  subtitle?: string;
}

export function usePdfExport() {
  const [isExporting, setIsExporting] = useState(false);

  const exportToPdf = useCallback(async (
    elementId: string,
    options: ExportOptions = {}
  ) => {
    const { 
      filename = "herd-projection-report.pdf",
      title = "Herd Projection Report",
      subtitle = "Generated by FHPS"
    } = options;

    setIsExporting(true);

    try {
      const element = document.getElementById(elementId);
      if (!element) {
        throw new Error("Element not found");
      }

      const canvas = await html2canvas(element, {
        scale: 2,
        useCORS: true,
        logging: false,
        backgroundColor: "#faf8f5",
      });

      const imgData = canvas.toDataURL("image/png");
      const pdf = new jsPDF({
        orientation: "portrait",
        unit: "mm",
        format: "a4",
      });

      const pageWidth = pdf.internal.pageSize.getWidth();
      const pageHeight = pdf.internal.pageSize.getHeight();
      const margin = 15;
      const contentWidth = pageWidth - (margin * 2);

      // Header
      pdf.setFillColor(59, 102, 67); // Primary green
      pdf.rect(0, 0, pageWidth, 35, "F");
      
      pdf.setTextColor(255, 255, 255);
      pdf.setFontSize(22);
      pdf.setFont("helvetica", "bold");
      pdf.text(title, margin, 18);
      
      pdf.setFontSize(10);
      pdf.setFont("helvetica", "normal");
      pdf.text(subtitle, margin, 28);
      
      // Date
      pdf.text(
        `Generated: ${new Date().toLocaleDateString("en-US", { 
          year: "numeric", 
          month: "long", 
          day: "numeric" 
        })}`,
        pageWidth - margin,
        28,
        { align: "right" }
      );

      // Content
      const imgWidth = contentWidth;
      const imgHeight = (canvas.height * imgWidth) / canvas.width;
      const startY = 45;

      // Handle multi-page content
      let remainingHeight = imgHeight;
      let currentY = startY;
      let sourceY = 0;

      while (remainingHeight > 0) {
        const availableHeight = pageHeight - currentY - margin;
        const drawHeight = Math.min(remainingHeight, availableHeight);
        const sourceHeight = (drawHeight / imgHeight) * canvas.height;

        // Create a cropped canvas for this page
        const croppedCanvas = document.createElement("canvas");
        croppedCanvas.width = canvas.width;
        croppedCanvas.height = sourceHeight;
        const ctx = croppedCanvas.getContext("2d");
        
        if (ctx) {
          ctx.drawImage(
            canvas,
            0, sourceY,
            canvas.width, sourceHeight,
            0, 0,
            canvas.width, sourceHeight
          );
          
          const croppedImgData = croppedCanvas.toDataURL("image/png");
          pdf.addImage(croppedImgData, "PNG", margin, currentY, imgWidth, drawHeight);
        }

        remainingHeight -= drawHeight;
        sourceY += sourceHeight;

        if (remainingHeight > 0) {
          pdf.addPage();
          currentY = margin;
        }
      }

      // Footer on last page
      pdf.setTextColor(120, 120, 120);
      pdf.setFontSize(8);
      pdf.text(
        "FHPS • Fibonacci-Based Herd Projection System",
        pageWidth / 2,
        pageHeight - 10,
        { align: "center" }
      );

      pdf.save(filename);
    } catch (error) {
      console.error("PDF export failed:", error);
      throw error;
    } finally {
      setIsExporting(false);
    }
  }, []);

  return { exportToPdf, isExporting };
}
